# Generated by Django 3.2.9 on 2021-11-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('phone_num', models.IntegerField(max_length=12)),
                ('matiral_status', models.CharField(choices=[('married', 'married'), ('not married', 'not married'), ('single', 'single')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('phone_num', models.IntegerField(max_length=12)),
                ('matiral_status', models.CharField(choices=[('married', 'married'), ('not married', 'not married'), ('single', 'single')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(max_length=8)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('baby', 'baby')], max_length=6)),
                ('code_wintering', models.IntegerField(blank=True, max_length=4)),
                ('flight_date', models.DateField(blank=True, max_length=8)),
                ('arrival_date', models.DateField(blank=True, max_length=8)),
                ('temperature', models.CharField(blank=True, max_length=4)),
                ('hibernation_timing', models.IntegerField(blank=True, max_length=3)),
                ('habibate', models.CharField(max_length=45)),
                ('about_of_habibate', models.TextField(max_length=1000)),
                ('ration_num', models.IntegerField(max_length=4)),
                ('ration_name', models.CharField(max_length=30)),
                ('ration_type', models.CharField(choices=[('baby feeding', 'baby feeding'), ('diet feeding', 'diet feeding'), ('enhanced feeding', 'enhanced feeding')], max_length=16)),
                ('caretaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.caretaker')),
                ('veterinrian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.veterinarian')),
            ],
        ),
    ]
