# Generated by Django 3.2.9 on 2021-11-04 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_pet_ration_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='code_wintering',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ration_num',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
