# Generated by Django 3.2.9 on 2021-11-04 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretaker',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='code_wintering',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ration_num',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='phone_num',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
