# Generated by Django 3.2.9 on 2021-11-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20211104_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='about_of_habibate',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
