# Generated by Django 3.2.9 on 2021-11-05 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_pet_about_of_habibate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='about_of_habibate',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='arrival_date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='code_wintering',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='flight_date',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hibernation_timing',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temperature',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
